software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  strapmeboots:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: strapmeboots
        version: 2:0.0.7
        depends:
          - ntp
          - curl
          - htop
          - mtr
          - aptitude
          - sudo
          - vim-nox
          - gdb
          - strace
          - mxm-utils
          - runit-common
          - apt-transport-s3
          - python-aws
        repos:
          - mxm-public
        target: install
