software_groups: &software
  - "base"

jobs:
  strapmeboots:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: strapmeboots
        repos:
          - mxm-public
        target: install
